apiVersion: v1
kind: Service
metadata:
  namespace: websocket-sample
  name: deliverer-svc
spec:
  selector:
    app: deliverer
  ports:
    - name: default-port
      protocol: TCP
      port: 3000
      targetPort: 3000
